[package]
name = "chess_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
chess = "3.2.0"
chrono = "0.4.38"
env_logger = "0.11.3"
lazy_static = "1.5.0"
log = "0.4.21"
rand = "0.8.5"
rayon = "1.10.0"
